BINANCE_API_KEY = 'KWEBS3XSsRGVHSfA8JoPn30fs5FFr2TGoQ4oAOYup0besfOLTPyQ6hzve5TMIgYx'
BINANCE_API_SECRET = 'tb7FeTWYNS9QQevzZPl0I8AFWwbTzN8FKVjMub9mmLqTY3gTUM5JvJOUA1UKBxaP'

OHLCV_COLS = ['timestamp', 'open', 'high', 'low', 'closed', 'volume']